# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_pass %>

development:
  <<: *default
  database: badblog5_development

test:
  <<: *default
  database: badblog5_test

production:
  <<: *default
  database: badblog_production
#  username: deploy
#  password: <%= ENV['TESTAPP_DATABASE_PASSWORD'] %>
