# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d633fccb1da8c250bd5666b403758633eda3c2da2322fa1d83baf838ff4944038ce1582065808c3183ea53be4bda0dfea7e9c15efcc690e43a50bdda5e342f0
  db_user: <%= ENV['PG_DB_USER'] %>
  db_pass: <%= ENV['PG_DB_PASS'] %>
test:
  secret_key_base: c885e1abfaa743c30216d156b5e770709bb2be9f6b1521ab2f2b0cd041877b8ab063dce3f9136869b745ee8ed0d82012c65c01619781ecb7c57be90243ee4b6e
  db_user: <%= ENV['PG_DB_USER'] %>
  db_pass: <%= ENV['PG_DB_PASS'] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_user: <%= ENV['PG_DB_USER'] %>
  db_pass: <%= ENV['PG_DB_PASS'] %>
  devise_secret_key: <%= ENV['DEVICE_CONFIG_SECRET_KEY'] %>
  blog_gmail_account: <%= ENV['BLOG_GMAIL_ACCOUNT'] %>
  blog_gmail_pass: <%= ENV['BLOG_GMAIL_PASS'] %>